apiVersion: v1
kind: ServiceAccount
metadata:
  name: kbit-integration-tests
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kbit-integration-tests
subjects:
- kind: ServiceAccount
  name: kbit-integration-tests
roleRef:
  kind: Role
  name: kbit-integration-tests
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kbit-integration-tests
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "kbit-integration-tests"
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1800
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: "kbit-integration-tests"
    spec:
      serviceAccountName: kbit-integration-tests
      containers:
      - name: "kbit-integration-tests"
        image: "image-registry.openshift-image-registry.svc:5000/kbit-devops/kbit-integration-tests"
        imagePullPolicy: Always
        env:
        - name: KBIT_API
          value: "http://127.0.0.1:8080"
        - name: K8S_IN_CLUSTER
          value: "true"
      restartPolicy: OnFailure