apiVersion: v1
kind: ServiceAccount
metadata:
  name: kbit-integration-tests
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kbit-integration-tests
subjects:
- kind: ServiceAccount
  name: kbit-integration-tests
roleRef:
  kind: Role
  name: kbit-integration-tests
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kbit-integration-tests
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]